# Generated by Django 5.2.13 on 2026-04-23 04:46

import apps.common.utils.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Merchant",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        default=apps.common.utils.crypto.generate_merchant_uuid,
                        editable=False,
                        max_length=42,
                        unique=True,
                    ),
                ),
                ("username", models.CharField(db_index=True, max_length=50, unique=True)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("phone_encrypted", models.CharField(default="", max_length=255)),
                ("store_name", models.CharField(default="", max_length=100)),
                ("store_address", models.CharField(default="", max_length=255)),
                ("avatar_url", models.URLField(default="", max_length=500)),
                ("quota_total", models.PositiveIntegerField(default=100, verbose_name="总配额")),
                ("quota_used", models.PositiveIntegerField(default=0, verbose_name="已用配额")),
                (
                    "quota_reset_at",
                    models.DateField(blank=True, null=True, verbose_name="配额重置日期"),
                ),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "禁用"), (1, "正常"), (2, "过期")], default=1
                    ),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_ip", models.CharField(blank=True, default="", max_length=45)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "商家",
                "verbose_name_plural": "商家管理",
                "db_table": "merchant",
            },
        ),
        migrations.CreateModel(
            name="SmsLog",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("code", models.CharField(max_length=6)),
                (
                    "purpose",
                    models.CharField(
                        choices=[("login", "登录"), ("bind_phone", "绑定手机")],
                        default="login",
                        max_length=20,
                    ),
                ),
                ("is_used", models.BooleanField(default=False)),
                ("ip_address", models.CharField(blank=True, default="", max_length=45)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expired_at", models.DateTimeField()),
                (
                    "merchant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sms_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "短信验证码",
                "db_table": "sms_log",
                "indexes": [
                    models.Index(
                        fields=["phone", "code", "is_used"], name="sms_log_phone_c24c54_idx"
                    ),
                    models.Index(fields=["expired_at"], name="sms_log_expired_d39639_idx"),
                ],
            },
        ),
    ]
