# Generated by Django 5.2.13 on 2026-04-09 06:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="last_login_ip",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="ip_address",
            field=models.CharField(blank=True, default="", max_length=45),
        ),
    ]
