# Generated by Django 5.2.13 on 2026-04-24 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchant",
            name="role",
            field=models.CharField(
                choices=[("merchant", "普通商家"), ("merchant_admin", "商家管理员")],
                default="merchant",
                max_length=20,
                verbose_name="用户角色",
            ),
        ),
        migrations.AlterField(
            model_name="smslog",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("login", "登录"),
                    ("bind_phone", "绑定手机"),
                    ("reset_password", "重置密码"),
                ],
                default="login",
                max_length=20,
            ),
        ),
    ]
