# Generated by Django 5.2.13 on 2026-04-24 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_merchant_role_alter_smslog_purpose"),
    ]

    operations = [
        migrations.AlterField(
            model_name="merchant",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "禁用"), (1, "正常"), (2, "过期"), (3, "待审核")], default=1
            ),
        ),
    ]
