# Generated by Django 5.2.13 on 2026-04-18 15:00

import apps.common.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TryOnClothing',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('record_id', models.BigIntegerField(db_index=True)),
                ('clothing_id', models.CharField(max_length=100)),
                ('is_custom', models.BooleanField(default=False)),
                ('category', models.CharField(max_length=30)),
                ('subcategory', models.CharField(max_length=30)),
                ('clothing_name', models.CharField(max_length=100)),
                ('clothing_color', models.CharField(default='#000000', max_length=30)),
                ('clothing_image', models.URLField(default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '试穿服装关联',
                'verbose_name_plural': '试穿服装关联管理',
                'db_table': 'tryon_clothing',
                'indexes': [models.Index(fields=['record_id'], name='tryon_cloth_record__0b8b92_idx'), models.Index(fields=['clothing_id'], name='tryon_cloth_clothin_3639eb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TryOnRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('uuid', models.CharField(default=apps.common.utils.crypto.generate_tryon_uuid, editable=False, max_length=42, unique=True)),
                ('merchant_id', models.BigIntegerField(db_index=True)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('avatar_url', models.URLField(max_length=500)),
                ('result_url', models.URLField(default='', max_length=500)),
                ('result_thumb_url', models.URLField(default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', '等待中'), ('processing', '处理中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20)),
                ('ai_engine', models.CharField(choices=[('aliyun', '阿里云'), ('tencent', '腾讯云'), ('seeddance', 'SeedDance')], default='aliyun', max_length=20)),
                ('task_id', models.CharField(default='', max_length=100)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('processing_time', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('quota_deducted', models.BooleanField(default=False)),
                ('is_saved', models.BooleanField(default=False)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('device_info', models.CharField(blank=True, default='', max_length=200)),
                ('user_agent', models.CharField(default='', max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '试穿记录',
                'verbose_name_plural': '试穿记录管理',
                'db_table': 'tryon_record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['merchant_id', 'session_id', 'created_at'], name='tryon_recor_merchan_3f20fc_idx'), models.Index(fields=['merchant_id', 'status'], name='tryon_recor_merchan_5829d5_idx'), models.Index(fields=['merchant_id', 'is_saved', 'created_at'], name='tryon_recor_merchan_cd192e_idx'), models.Index(fields=['task_id'], name='tryon_recor_task_id_46af32_idx'), models.Index(fields=['session_id', 'created_at'], name='tryon_recor_session_f192fa_idx')],
            },
        ),
    ]
