# Generated by Django 5.2.13 on 2026-04-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tryon", "0003_add_result_original_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="tryonclothing",
            name="clothing_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
