# Generated by Django 5.2.13 on 2026-04-28 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tryon", "0004_add_clothing_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="tryonrecord",
            name="avatar_source",
            field=models.CharField(
                choices=[("system", "系统模特"), ("user", "用户上传"), ("history", "历史记录")],
                default="user",
                help_text="头像来源：system-系统模特, user-用户上传, history-历史记录",
                max_length=20,
            ),
        ),
    ]
