# Generated by Django 5.2.13 on 2026-04-23 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileUploadRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "md5_hash",
                    models.CharField(
                        db_index=True,
                        help_text="用于去重，相同 MD5 复用已有文件",
                        max_length=32,
                        verbose_name="文件 MD5",
                    ),
                ),
                (
                    "storage_type",
                    models.CharField(
                        choices=[("local", "本地存储"), ("oss", "阿里云 OSS")],
                        default="local",
                        max_length=10,
                        verbose_name="存储类型",
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        help_text="本地: 相对路径; OSS: object key",
                        max_length=500,
                        verbose_name="存储路径",
                    ),
                ),
                (
                    "access_url",
                    models.CharField(
                        help_text="本地: /media/xxx; OSS: 公网 URL",
                        max_length=1000,
                        verbose_name="访问 URL",
                    ),
                ),
                (
                    "tenant_id",
                    models.CharField(
                        db_index=True,
                        help_text="商户/用户标识，用于隔离",
                        max_length=50,
                        verbose_name="租户 ID",
                    ),
                ),
                (
                    "folder",
                    models.CharField(
                        db_index=True,
                        help_text="如 avatars, clothes, results",
                        max_length=100,
                        verbose_name="存储文件夹",
                    ),
                ),
                (
                    "file_category",
                    models.CharField(
                        choices=[
                            ("avatar", "人物照片"),
                            ("clothing", "服装图片"),
                            ("result", "试穿结果"),
                            ("other", "其他"),
                        ],
                        default="other",
                        max_length=20,
                        verbose_name="文件用途",
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(default=0, verbose_name="文件大小(字节)"),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="文件类型"
                    ),
                ),
                (
                    "file_ext",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如 .png, .jpg, .webp",
                        max_length=10,
                        verbose_name="文件扩展名",
                    ),
                ),
                (
                    "width",
                    models.PositiveIntegerField(
                        default=0, help_text="仅图片类型有效", verbose_name="图片宽度"
                    ),
                ),
                (
                    "height",
                    models.PositiveIntegerField(
                        default=0, help_text="仅图片类型有效", verbose_name="图片高度"
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0, help_text="相同 MD5 的重复上传次数", verbose_name="命中次数"
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后访问时间"),
                ),
                (
                    "ref_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如 tryon_record, clothing",
                        max_length=30,
                        verbose_name="关联类型",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="关联对象的 UUID 或 ID",
                        max_length=50,
                        verbose_name="关联 ID",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="如 web, api, import",
                        max_length=30,
                        verbose_name="上传来源",
                    ),
                ),
                (
                    "client_ip",
                    models.CharField(
                        blank=True, default="", max_length=45, verbose_name="客户端 IP"
                    ),
                ),
            ],
            options={
                "verbose_name": "文件上传记录",
                "verbose_name_plural": "文件上传记录",
                "db_table": "common_file_upload_record",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tenant_id", "md5_hash"], name="idx_tenant_md5"),
                    models.Index(fields=["tenant_id", "folder"], name="idx_tenant_folder"),
                    models.Index(fields=["tenant_id", "file_category"], name="idx_tenant_category"),
                    models.Index(fields=["storage_type", "folder"], name="idx_storage_folder"),
                    models.Index(fields=["-last_accessed_at"], name="idx_last_access"),
                    models.Index(fields=["-created_at"], name="idx_created"),
                    models.Index(fields=["ref_type", "ref_id"], name="idx_ref"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant_id", "md5_hash", "storage_type"),
                        name="uq_tenant_md5_storage",
                    )
                ],
            },
        ),
    ]
