# Generated by Django 5.2.13 on 2026-04-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OSSFileCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                (
                    "md5",
                    models.CharField(
                        db_index=True, max_length=32, unique=True, verbose_name="文件 MD5"
                    ),
                ),
                ("oss_key", models.CharField(max_length=500, verbose_name="OSS 文件路径")),
                ("public_url", models.URLField(max_length=1000, verbose_name="公网访问 URL")),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        help_text="用于统计和监控", verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        blank=True, default="", max_length=100, verbose_name="文件类型"
                    ),
                ),
                (
                    "upload_count",
                    models.PositiveIntegerField(
                        default=1, help_text="相同文件的请求次数", verbose_name="上传次数"
                    ),
                ),
                (
                    "last_accessed_at",
                    models.DateTimeField(auto_now=True, verbose_name="最后访问时间"),
                ),
            ],
            options={
                "verbose_name": "OSS 文件缓存",
                "verbose_name_plural": "OSS 文件缓存",
                "db_table": "common_oss_file_cache",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["md5"], name="common_oss__md5_a9af68_idx"),
                    models.Index(
                        fields=["-last_accessed_at"], name="common_oss__last_ac_9df3e6_idx"
                    ),
                ],
            },
        ),
    ]
