# Generated by Django 5.2.13 on 2026-04-24 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploadrecord",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
        ),
        migrations.AddField(
            model_name="fileuploadrecord",
            name="is_deleted",
            field=models.BooleanField(
                default=False, help_text="软删除标记，不会真正删除文件", verbose_name="是否已删除"
            ),
        ),
    ]
