# Generated by Django 5.2.13 on 2026-04-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_add_soft_delete_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelPhoto",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100, verbose_name="模特名称")),
                ("image_url", models.URLField(max_length=500, verbose_name="模特照片URL")),
                (
                    "image_thumb_url",
                    models.URLField(
                        blank=True, default="", max_length=500, verbose_name="缩略图URL"
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "男"), ("female", "女")],
                        default="female",
                        max_length=10,
                        verbose_name="性别",
                    ),
                ),
            ],
            options={
                "verbose_name": "模特照片",
                "verbose_name_plural": "模特照片管理",
                "db_table": "common_model_photo",
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="fileuploadrecord",
            name="signed_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="缓存的签名 URL，过期后重新生成",
                max_length=2000,
                verbose_name="缓存的签名 URL",
            ),
        ),
        migrations.AddField(
            model_name="fileuploadrecord",
            name="signed_url_expires",
            field=models.DateTimeField(
                blank=True,
                help_text="签名 URL 的过期时间",
                null=True,
                verbose_name="签名 URL 过期时间",
            ),
        ),
    ]
