# Generated by Django 5.2.13 on 2026-04-22 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_file_upload_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fileuploadrecord',
            name='uq_tenant_md5',
        ),
        migrations.AddConstraint(
            model_name='fileuploadrecord',
            constraint=models.UniqueConstraint(fields=('tenant_id', 'md5_hash', 'storage_type'), name='uq_tenant_md5_storage'),
        ),
    ]
