# Generated by Django 5.2.13 on 2026-04-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0003_add_signed_url_cache"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelphoto",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="models/", verbose_name="模特照片"
            ),
        ),
        migrations.AlterField(
            model_name="modelphoto",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, verbose_name="模特照片URL"),
        ),
    ]
