# Generated by Django 5.2.13 on 2026-04-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_modelphoto_image_alter_modelphoto_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileuploadrecord",
            name="is_public",
            field=models.BooleanField(
                default=False,
                help_text="公开文件不需要签名 URL，私有文件需要签名 URL",
                verbose_name="是否公开",
            ),
        ),
    ]
