# Generated by Django 5.2.13 on 2026-04-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0006_modelphoto_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelphoto",
            name="image_key",
            field=models.CharField(
                blank=True,
                default='',
                help_text='用于生成的图片唯一标识，格式: storage_type:md5',
                max_length=100,
                verbose_name='图片Key',
            ),
        ),
    ]
