# Generated by Django 5.2.13 on 2026-04-26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0007_modelphoto_image_key"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelphoto",
            name="image",
        ),
    ]
