# Generated by Django 5.2.13 on 2026-04-24 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("admin_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminoperationlog",
            new_name="admin_opera_admin_i_aaf87b_idx",
            old_name="idx_admin_time",
        ),
        migrations.RenameIndex(
            model_name="adminoperationlog",
            new_name="admin_opera_action_d278bc_idx",
            old_name="idx_action_time",
        ),
        migrations.RenameIndex(
            model_name="adminoperationlog",
            new_name="admin_opera_target__69d344_idx",
            old_name="idx_target",
        ),
        migrations.RenameIndex(
            model_name="quotahistory",
            new_name="admin_quota_merchan_b7486f_idx",
            old_name="idx_merchant_time",
        ),
    ]
