# Generated by Django 5.2.13 on 2026-05-27 03:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Clothing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("merchant_id", models.BigIntegerField(db_index=True, verbose_name="商家ID")),
                ("name", models.CharField(max_length=200, verbose_name="服装名称")),
                ("category", models.CharField(max_length=50, verbose_name="分类")),
                ("subcategory", models.CharField(max_length=50, verbose_name="子分类")),
                ("color", models.CharField(default="#000000", max_length=50, verbose_name="颜色")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("sizes", models.JSONField(default=list, verbose_name="尺码列表")),
                (
                    "source",
                    models.CharField(
                        choices=[("wardrobe", "衣橱"), ("upload", "临时上传")],
                        default="wardrobe",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                ("is_deleted", models.BooleanField(default=False, verbose_name="是否删除")),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="删除时间"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "file",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="common.filerecord",
                        verbose_name="关联文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "服装",
                "verbose_name_plural": "服装管理",
                "db_table": "wardrobe_clothing",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["merchant_id", "category"], name="wardrobe_cl_merchan_98d216_idx"
                    ),
                    models.Index(
                        fields=["merchant_id", "is_active"], name="wardrobe_cl_merchan_d0f3f1_idx"
                    ),
                ],
            },
        ),
    ]
