# Generated by Django 5.2.13 on 2026-04-23 04:46

import apps.common.utils.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PresetClothing",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tops", "上装"),
                            ("bottoms", "下装"),
                            ("dresses", "连衣裙"),
                            ("outerwear", "外套"),
                            ("shoes", "鞋"),
                            ("accessories", "配饰"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subcategory", models.CharField(max_length=30)),
                ("name_i18n", models.JSONField(default=dict)),
                ("color", models.CharField(default="#000000", max_length=30)),
                ("image_url", models.URLField(default="", max_length=500)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "预设服装",
                "verbose_name_plural": "预设服装管理",
                "db_table": "preset_clothing",
                "ordering": ["category", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="Clothing",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "uuid",
                    models.CharField(
                        default=apps.common.utils.crypto.generate_clothing_uuid,
                        editable=False,
                        max_length=42,
                        unique=True,
                    ),
                ),
                ("merchant_id", models.BigIntegerField(db_index=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("tops", "上装"),
                            ("bottoms", "下装"),
                            ("dresses", "连衣裙"),
                            ("outerwear", "外套"),
                            ("shoes", "鞋"),
                            ("accessories", "配饰"),
                        ],
                        max_length=30,
                    ),
                ),
                ("subcategory", models.CharField(max_length=30)),
                ("name", models.CharField(max_length=100)),
                ("color", models.CharField(default="#000000", max_length=30)),
                ("image_url", models.URLField(default="", max_length=500)),
                ("image_thumb_url", models.URLField(default="", max_length=500)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("preset", "预设"),
                            ("custom", "自定义"),
                            ("wardrobe", "衣橱上传"),
                        ],
                        default="preset",
                        max_length=20,
                    ),
                ),
                ("file_hash", models.CharField(default="", max_length=64)),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "服装",
                "verbose_name_plural": "服装管理",
                "db_table": "clothing",
                "ordering": ["-sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["merchant_id", "category", "is_active"],
                        name="clothing_merchan_42688b_idx",
                    ),
                    models.Index(
                        fields=["merchant_id", "category", "subcategory", "is_active"],
                        name="clothing_merchan_156a22_idx",
                    ),
                    models.Index(
                        fields=["merchant_id", "sort_order"], name="clothing_merchan_a31832_idx"
                    ),
                ],
            },
        ),
    ]
