# Generated by Django 5.2.13 on 2026-04-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wardrobe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothing',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='服装价格', max_digits=10),
        ),
        migrations.AddField(
            model_name='clothing',
            name='sizes',
            field=models.CharField(blank=True, default='', help_text='可用尺码，逗号分隔，如：S,M,L,XL', max_length=100),
        ),
    ]
